on:
    workflow_dispatch:
name: Update frontend's types.json
jobs:
    createPullRequest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Pull latest types.json
              run: |
                  git clone https://github.com/GopherJ/github-actions-tests
                  cd github-actions-tests
                  curl -fLo resources/types.json https://raw.githubusercontent.com/parallel-finance/parallel/master/resources/types.json
            - name: Check for modified files
              id: git-check
              working-directory: github-actions-tests
              run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
            - name: Push latest changes
              run: |
                  set -x
                  git config --global user.name "Github Actions"
                  git config --global user.email "Github Actions"
                  cd github-actions-tests
                  if [ -z "$(git status --porcelain)" ]
                    then
                      echo "nothing to update."
                  else
                      git commit -am "update types.json"
                  fi
                  git push "https://${{ secrets.PAT }}@github.com/GopherJ/github-actions-tests.git" HEAD:main
